dummy pr to test codecov on workflow 4

diff --git a/.github/workflows/require_coverage.yml b/.github/workflows/require_coverage.yml
--- a/.github/workflows/require_coverage.yml
+++ b/.github/workflows/require_coverage.yml
@@ -22,8 +22,21 @@ jobs:
       - name: Run coverage extraction script
         id: extract_coverage
         run: |
+            COVERAGE=$(
             node -e "
             import { extractCoverage } from '@nicolawealth/code_coverage_extractor';
-            extractCoverage('./coverage/coverage-final.json', './codecov/badge.json');
-            "
+            const result = extractCoverage('./coverage/coverage-final.json', './codecov/badge.json');
+            console.log(result);
+            ")
+          COVERAGE=$(echo $COVERAGE | xargs)
+          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
+
+      - name: Confirm Coverage Value
+        run: |
+          if [ "$COVERAGE" -ne 100 ]; then
+            echo "Assertion failed: Coverage is not 100% (Actual: $COVERAGE%)"
+            exit 1
+          else
+            echo "Assertion passed: Coverage is 100%"
+          fi
           
